---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart user-service
  ansible.builtin.systemd:
    name: user-service
    state: restarted

- name: Notify dependent services of user-service restart
  ansible.builtin.debug:
    msg: "User service has been restarted."

- name: Wait for user-service to be available
  ansible.builtin.uri:
    url: "http://{{ inventory_hostname }}:8000/actuator/health"
    status_code: 200
    method: GET
  register: user_service_health
  retries: 5
  delay: 10
  until: user_service_health.status == 200
