---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/dev_key.pem
    environment: dev
  children:
    api_gateway:
      hosts:
        dev-api-gateway-1:
          ansible_host: 192.168.1.10
    eureka_server:
      hosts:
        dev-eureka-server-1:
          ansible_host: 192.168.1.11
    user_service:
      hosts:
        dev-user-service-1:
          ansible_host: 192.168.1.12
    payment_service:
      hosts:
        dev-payment-service-1:
          ansible_host: 192.168.1.13
    notification_service:
      hosts:
        dev-notification-service-1:
          ansible_host: 192.168.1.14
    frontend:
      hosts:
        dev-frontend-1:
          ansible_host: 192.168.1.15
    kubernetes_masters:
      hosts:
        dev-k8s-master-1:
          ansible_host: 192.168.1.20
