---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  listen: "restart ssh"
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "reload systemd"
